// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Pelicula struct {
	ID              int32   `json:"id"`
	Titulo          string  `json:"titulo"`
	Descripcion     string  `json:"descripcion"`
	Duracion        int32   `json:"duracion"`
	Actores         string  `json:"actores"`
	Genero          string  `json:"genero"`
	AnioLanzamiento int32   `json:"anio_lanzamiento"`
	Puntaje         float64 `json:"puntaje"`
}
