// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createPelicula = `-- name: CreatePelicula :one
INSERT INTO peliculas (titulo, descripcion, duracion, actores, genero, anio_lanzamiento, puntaje)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, titulo, descripcion, duracion, actores, genero, anio_lanzamiento, puntaje
`

type CreatePeliculaParams struct {
	Titulo          string  `json:"titulo"`
	Descripcion     string  `json:"descripcion"`
	Duracion        int32   `json:"duracion"`
	Actores         string  `json:"actores"`
	Genero          string  `json:"genero"`
	AnioLanzamiento int32   `json:"anio_lanzamiento"`
	Puntaje         float64 `json:"puntaje"`
}

func (q *Queries) CreatePelicula(ctx context.Context, arg CreatePeliculaParams) (Pelicula, error) {
	row := q.db.QueryRowContext(ctx, createPelicula,
		arg.Titulo,
		arg.Descripcion,
		arg.Duracion,
		arg.Actores,
		arg.Genero,
		arg.AnioLanzamiento,
		arg.Puntaje,
	)
	var i Pelicula
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Duracion,
		&i.Actores,
		&i.Genero,
		&i.AnioLanzamiento,
		&i.Puntaje,
	)
	return i, err
}

const deletePelicula = `-- name: DeletePelicula :exec
DELETE FROM peliculas WHERE id = $1
`

func (q *Queries) DeletePelicula(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePelicula, id)
	return err
}

const getPelicula = `-- name: GetPelicula :one
SELECT id, titulo, descripcion, duracion, actores, genero, anio_lanzamiento, puntaje FROM peliculas WHERE id = $1
`

func (q *Queries) GetPelicula(ctx context.Context, id int32) (Pelicula, error) {
	row := q.db.QueryRowContext(ctx, getPelicula, id)
	var i Pelicula
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Duracion,
		&i.Actores,
		&i.Genero,
		&i.AnioLanzamiento,
		&i.Puntaje,
	)
	return i, err
}

const listPeliculas = `-- name: ListPeliculas :many
SELECT id, titulo, descripcion, duracion, actores, genero, anio_lanzamiento, puntaje FROM peliculas ORDER BY titulo
`

func (q *Queries) ListPeliculas(ctx context.Context) ([]Pelicula, error) {
	rows, err := q.db.QueryContext(ctx, listPeliculas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pelicula
	for rows.Next() {
		var i Pelicula
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Duracion,
			&i.Actores,
			&i.Genero,
			&i.AnioLanzamiento,
			&i.Puntaje,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePelicula = `-- name: UpdatePelicula :exec
UPDATE peliculas
SET titulo = $2, descripcion = $3, duracion = $4, actores = $5, genero = $6, anio_lanzamiento = $7, puntaje = $8
WHERE id = $1
`

type UpdatePeliculaParams struct {
	ID              int32   `json:"id"`
	Titulo          string  `json:"titulo"`
	Descripcion     string  `json:"descripcion"`
	Duracion        int32   `json:"duracion"`
	Actores         string  `json:"actores"`
	Genero          string  `json:"genero"`
	AnioLanzamiento int32   `json:"anio_lanzamiento"`
	Puntaje         float64 `json:"puntaje"`
}

func (q *Queries) UpdatePelicula(ctx context.Context, arg UpdatePeliculaParams) error {
	_, err := q.db.ExecContext(ctx, updatePelicula,
		arg.ID,
		arg.Titulo,
		arg.Descripcion,
		arg.Duracion,
		arg.Actores,
		arg.Genero,
		arg.AnioLanzamiento,
		arg.Puntaje,
	)
	return err
}
